name: update

on:
  schedule:
    #- cron: '0 4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sh ./update.sh
